### ISSUE TITLE
GitHub Integration - Frontend Implementation

### ISSUE THREAD

**Issue by LouisIV** [Hackerstat/website#10]
- [x] Determine what we want to show from a user's Github Profile
- [x] Create a card for this integration

**Comment by Cgunter1** [comment]
# Changes
1. Implemented ability for users to show offer their GitHub's personal info, repos, and contribution graph.
2. Also, it has a verification logo that shows GitHub is verified.
<img width="425" alt="Screen Shot 2021-07-07 at 11 00 45 AM" src="https://user-images.githubusercontent.com/22761143/124807703-eb004180-df12-11eb-9ff2-fa4fc30594b9.png">
