### ISSUE TITLE
WakaTime Integration - Frontend Implementation

### ISSUE THREAD

**Issue by LouisIV** [Hackerstat/website#3]
- [x] Add WakaTime to the integrated profiles list.
- [x] Send the WakaTime username to the backend
- [x] Display data from WakaTime
  - [x] Total time
  - [x] Graphs

**Comment by Cgunter1** [comment]
# Changes
1. Implemented ability for user's to set their WakaTime integration info in the user's integration settings. Also, implemented validation to make sure that the integration info for WakaTime given (i.e. HTTP urls) is valid or not.
2. Implemented display of that WakaTime data for languages used (i.e. bar graph) and coding activity (i.e. pie graph).
