### ISSUE TITLE
WakaTime Integration - API Implementation

### ISSUE THREAD

**Issue by LouisIV** [Hackerstat/website#4]
#### API

[Users](https://wakatime.com/developers#users)

Check if a user has a public account/test if the account exists.

[Get Summary of activity for a user](https://wakatime.com/developers#summaries)

> A user's coding activity for the given time range as an array of summaries segmented by day.

[Get User Stats](https://wakatime.com/developers#stats)

> A user's coding activity for the given time range. range can be one of last_7_days, last_30_days, last_6_months, or last_year. For accounts subscribed to the free plan, time ranges >= one year are updated on the first request. It’s best to always check is_up_to_date and retry your request when the response is stale.

**Comment by Cgunter1** [comment]
# API
1.  Implemented ability for user to their retrieve WakaTime HTTP urls for coding activity and language used.
2. Also, implemented ability to retrieve WakaTime data from a user's profile.
