### ISSUE TITLE
GitHub Integration - API Implementation

### ISSUE THREAD

**Issue by LouisIV** [Hackerstat/website#7]
- [x] Get GitHub API key
- [x] Determine required routes
- [x] Get User's contributions to create a contribution graph

#### Contribution Graph

[User](https://docs.github.com/en/graphql/reference/objects#user)

- [Contributions](https://docs.github.com/en/graphql/reference/objects#contributionscollection)

  - [Calendar](https://docs.github.com/en/graphql/reference/objects#contributioncalendar)

**Comment by Cgunter1** [comment]
# Changes
This issue is a duplicate of #9. Look over there for more info of why this issue is closed.
