### ISSUE TITLE
GitHub Integration

### ISSUE THREAD

**Issue by LouisIV** [Hackerstat/website#9]
#### Focus

* Show a user's # of stars, # of followers
* Show a user's top projects
  * Check the contents of repos for common tools / deps.
* Get a user's contribution graph

#### SUBTASKS
- [x] #7
- [x] #10

**Comment by Cgunter1** [comment]
# Changes
1. Implemented a user's ability to verify the GitHub account and retrieve their GitHub account's info and repos.
2. Implemented the presentation of a user's contribution graph, list of repos and associated info and personal info.
